"""
Training run plots for thesis — one figure per policy family.
Layout: 4 rows × 2 cols (8 metrics), shared x-axis.
Stitched run boundaries are marked with dotted vertical lines and circled run numbers.
"""

import os
import pathlib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

BASE_PATH = "master_thesis/modules/subgoal_predictor/runs_pub"
OUTPUT_DIR = pathlib.Path(__file__).parent
BIN_SIZE = 20

# Set to a list of policy keys to generate only those, e.g. ["A_bi_gnn"].
# None generates all entries in POLICY_CONFIGS.
POLICIES_TO_RUN = None

# Toggle circled run numbers at boundaries.
# False = dotted lines only; colours still distinguish runs.
SHOW_RUN_NUMBERS = True

# Draw a vertical dashed connector between the last value of run k and the first
# value of run k+1 at each boundary — makes the jump (or continuity) explicit.
SHOW_RUN_CONNECTORS = False

# Run colour order: first run = red, second = blue, third = teal/green, then extras.
# Extend if a policy has more runs than colours listed here.
RUN_PALETTE = [
    '#e63946',  # red
    '#457b9d',  # blue
    '#2a9d8f',  # teal-green
    '#f4a261',  # orange
    '#a8dadc',  # light blue
    '#c77dff',  # purple
    '#e9c46a',  # yellow
    '#264653',  # dark slate
]

# Metric tag → display label, row-major 2×3: top row = outcomes, bottom row = behaviour
METRICS = [
    ('train/mean_reward',      'Mean Reward'),
    ('train/frac_terminated',  'Frac. Terminated'),
    ('train/mean_entropy_pos', 'Position Entropy'),
    ('train/mean_makespan',    'Mean Makespan [steps]'),
    ('train/mean_wait_time',   'Mean Wait Time [steps]'),
    ('train/mean_n_crossed',   'Mean Crossings'),
]

# Axes where y should be clipped to [0, 1]
UNIT_METRICS = {'Frac. Terminated'}

# Each entry in "runs": (name under BASE_PATH, legend label).
# Paths match the published names in runs_pub/ (generated by publish_runs.py).
# ★ = checkpoint used for evaluation; included in label for the LaTeX table reference.
POLICY_CONFIGS = {
    "A_mlp": {
        "title": "MLP — 5n1g (2×2, 5 agents, 1 gap)",
        "runs": [
            ("A_mlp_v1", "v1"),   # ★
        ],
    },
    "A_mlp_discrete": {
        "title": "MLP (discrete wait) — 5n1g architectural exploration",
        "runs": [
            ("A_mlp_disc_v1", "v1"),
            ("A_mlp_disc_v2", "v2"),
        ],
    },
    "A_hom_gnn_discrete": {
        "title": "Homogeneous GNN (discrete wait) — 5n1g architectural exploration",
        "runs": [
            ("A_hom_gnn_disc_v1", "v1"),
        ],
    },
    "A_hom_gnn": {
        "title": "Homogeneous GNN — 5n1g (2×2, 5 agents, 1 gap)",
        "runs": [
            ("A_hom_gnn_v1", "v1"),
            ("A_hom_gnn_v2", "v2"),
            ("A_hom_gnn_v3", "v3"),
            ("A_hom_gnn_v4", "v4"),
            ("A_hom_gnn_v5", "v5"),
            ("A_hom_gnn_v6", "v6"),   # ★
        ],
    },
    "A_bi_gnn": {
        "title": "Bipartite GNN — 5n1g (2×2, 5 agents, 1 gap)",
        "runs": [
            ("A_bi_gnn_v1", "v1"),
            ("A_bi_gnn_v2", "v2"),   # ★
            ("A_bi_gnn_v3", "v3"),
            ("A_bi_gnn_v4", "v4"),
            ("A_bi_gnn_v5", "v5"),
        ],
    },
    "C_bi_gnn": {
        "title": "Bipartite GNN — 8n2g (3×3, 8 agents, 2 gaps)",
        "runs": [
            ("C_bi_gnn_v1", "v1"),
            ("C_bi_gnn_v2", "v2"),
            ("C_bi_gnn_v3", "v3"),   # ★
            ("C_bi_gnn_v4", "v4"),
        ],
    },
    "D_bi_gnn": {
        "title": "Bipartite GNN — 10n1g (3×3, 10 agents, 1 gap)",
        "runs": [
            ("D_bi_gnn_v1", "v1"),
            ("D_bi_gnn_v2", "v2"),
            ("D_bi_gnn_v3", "v3"),   # ★
            ("D_bi_gnn_v4", "v4"),
        ],
    },
}


def load_run_data(run_dir: str, run_name: str) -> pd.DataFrame:
    ea = EventAccumulator(run_dir)
    ea.Reload()
    available = set(ea.Tags().get('scalars', []))

    run_df = None
    for tag, label in METRICS:
        if tag not in available:
            continue
        df = pd.DataFrame(ea.Scalars(tag))
        df = df.rename(columns={'value': label, 'step': 'Step'})[['Step', label]]
        run_df = df if run_df is None else pd.merge(run_df, df, on='Step', how='outer')

    if run_df is None:
        return pd.DataFrame()

    run_df['Run'] = run_name
    return run_df.sort_values('Step').reset_index(drop=True)


def stitch_runs(runs_config: list, bin_size: int = BIN_SIZE):
    """Concatenate runs into a single continuous step axis with bin-aligned offsets.

    Returns (df, boundaries, run_midpoints):
      boundaries    — x positions of the dividers between runs (len = n_runs - 1)
      run_midpoints — x centre of each run segment (len = n_runs), used for number labels
    """
    all_data = []
    boundaries = []
    run_midpoints = []
    current_offset = 0

    for path, name in runs_config:
        print(f"  Loading '{name}' from {path} …")
        df = load_run_data(path, name)
        if df.empty:
            print(f"    [warn] no data found, skipping")
            continue

        run_start = current_offset
        df['Step'] = df['Step'] - df['Step'].min() + current_offset
        all_data.append(df)

        max_step = df['Step'].max()
        run_midpoints.append((run_start + max_step) / 2)

        last_bin_x = (max_step // bin_size) * bin_size
        boundary_pos = last_bin_x + bin_size / 2
        boundaries.append(boundary_pos)
        current_offset = last_bin_x + bin_size

    if not all_data:
        return pd.DataFrame(), [], []

    return pd.concat(all_data, ignore_index=True), boundaries[:-1], run_midpoints


def _add_vlines(ax, boundaries: list):
    """Draw vertical dotted lines at run boundaries (called during main plot loop)."""
    for b in boundaries:
        ax.axvline(x=b, color='black', linestyle=':', alpha=0.65, linewidth=1.4)


def _draw_connectors(ax, df: pd.DataFrame, boundaries: list, run_order: list,
                     label: str, palette: list):
    """Draw a solid vertical segment at each boundary in the colour of the incoming run."""
    if not SHOW_RUN_CONNECTORS or label not in df.columns:
        return
    for k, b in enumerate(boundaries):
        run_a, run_b = run_order[k], run_order[k + 1]

        mask_a = (df['Run'] == run_a) & df[label].notna()
        mask_b = (df['Run'] == run_b) & df[label].notna()
        if not mask_a.any() or not mask_b.any():
            continue

        last_bin  = df.loc[mask_a, 'Binned Step'].max()
        first_bin = df.loc[mask_b, 'Binned Step'].min()
        y_end   = df.loc[mask_a & (df['Binned Step'] == last_bin),  label].mean()
        y_start = df.loc[mask_b & (df['Binned Step'] == first_bin), label].mean()

        ax.plot([b, b], [y_end, y_start],
                color=palette[k + 1], linestyle='-', linewidth=2.0, alpha=0.9, zorder=5)


def _add_run_numbers(axes_row: list, run_midpoints: list):
    """Add circled run numbers above the top-row axes (called AFTER tight_layout).

    Placing annotations after tight_layout means tight_layout never accounts for
    the out-of-axes content and won't add unwanted space below the suptitle.
    """
    if not SHOW_RUN_NUMBERS:
        return
    for ax in axes_row:
        for k, mid in enumerate(run_midpoints):
            ax.text(
                mid, 1.02, str(k + 1),
                transform=ax.get_xaxis_transform(),
                ha='center', va='bottom',
                fontsize=7, fontweight='bold',
                bbox=dict(boxstyle='circle,pad=0.18', fc='white', ec='#333333', lw=0.9),
                clip_on=False,
            )


def plot_policy(df: pd.DataFrame, boundaries: list, run_midpoints: list, title: str, output_path: pathlib.Path):
    bin_size = BIN_SIZE
    df = df.copy()
    df['Binned Step'] = (df['Step'] // bin_size) * bin_size

    sns.set_theme(style="ticks")
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Palatino", "serif"],
        "axes.titlesize": 13,
        "axes.labelsize": 10,
        "axes.facecolor": "white",
        "figure.facecolor": "white",
        "axes.edgecolor": "black",
        "axes.linewidth": 0.9,
        "xtick.color": "black",
        "ytick.color": "black",
        "xtick.direction": "out",
        "ytick.direction": "out",
    })

    n_rows, n_cols = 2, 3
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(13, 7), sharex=True,
                             gridspec_kw={'hspace': 0.45, 'wspace': 0.35})
    fig.suptitle(title, fontsize=15, fontweight='bold', y=1.005)

    run_order = list(dict.fromkeys(df['Run']))  # ordered unique run names
    n_runs = len(run_order)
    palette = RUN_PALETTE[:n_runs]

    for idx, (tag, label) in enumerate(METRICS):
        row, col = divmod(idx, n_cols)
        ax = axes[row, col]

        if label not in df.columns or df[label].isna().all():
            ax.text(0.5, 0.5, 'no data', transform=ax.transAxes,
                    ha='center', va='center', color='gray', fontsize=9)
            ax.set_title(label, fontweight='bold', pad=20)
            _add_vlines(ax, boundaries)
            sns.despine(ax=ax)
            continue

        sns.lineplot(
            data=df, x='Binned Step', y=label, hue='Run', ax=ax,
            linewidth=2.0, errorbar='sd', legend=False, palette=palette,
        )

        ax.set_title(label, fontweight='bold', pad=20)
        ax.set_ylabel('')

        if label in UNIT_METRICS:
            ax.set_ylim(0, 1.05)

        _add_vlines(ax, boundaries)
        _draw_connectors(ax, df, boundaries, run_order, label, palette)
        sns.despine(ax=ax)

        if row == n_rows - 1:
            ax.set_xlabel('Cumulative PPO Updates', fontsize=10)

    from matplotlib.lines import Line2D
    legend_handles = [Line2D([0], [0], color=palette[i], linewidth=2.0) for i in range(n_runs)]
    fig.legend(legend_handles, run_order,
               loc='lower center', bbox_to_anchor=(0.5, 0.0),
               ncol=min(n_runs, 8), frameon=False, fontsize=10)

    plt.tight_layout(rect=[0, 0.06, 1, 1])
    fig.savefig(output_path, bbox_inches='tight', dpi=200)
    print(f"  → saved {output_path.name}")
    plt.close(fig)


if __name__ == "__main__":
    configs = {k: v for k, v in POLICY_CONFIGS.items()
               if POLICIES_TO_RUN is None or k in POLICIES_TO_RUN}
    for policy_key, cfg in configs.items():
        print(f"\n{'='*60}")
        print(f"Policy: {policy_key}")

        full_paths = [(os.path.join(BASE_PATH, p), n) for p, n in cfg["runs"]]
        df, boundaries, run_midpoints = stitch_runs(full_paths)

        if df.empty:
            print("  [skip] no data loaded")
            continue

        out = OUTPUT_DIR / f"training_{policy_key}.pdf"
        plot_policy(df, boundaries, run_midpoints, cfg["title"], out)

    print("\nDone.")
