testbed:
  id: lab
  size:
    x: [ 0 , 3 ]
    y: [ 0 , 3 ]


robots:
  autostart: false
  autostop: false

extensions:
  display: true
  limbobar: true
  timecode: false

simulation:
  enabled: true
  Ts: 0.01
  obstacles:
    - id: box1_sim
      type: box
      size: [ 1, 0.5 ]
      state: [ 1,1, 1.57 ]
    - id: box2_sim
      type: box
      size: [ 1, 0.5 ]
      state: [ 2,1, 1.57 ]
  robots: null

tracker:
  enabled: true
  server: palantir.lan
  sample_rate: 30

tracked_objects:
  origin: bilbo-origin
  limbo_bar: bilbo-limbo-bar
  boxes:
    - box-1
    - box-2
  robots:
    - bilbo2

mdns:
  enabled: true
  hostname: bilbolab  # Will be accessible as bilbolab.local
  # To access without port (bilbolab.local/gui instead of bilbolab.local:8400/gui),
  # set use_port_80 to true. This requires running the application with sudo.
  use_port_80: true